version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:15-alpine
    container_name: postgres-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    command: -p 5433
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
